/**
 * OnlyOffice document key format:
 *   doc:      "doc_<id>_v<N>_<timestamp>"   — N = OSS version the session was opened on
 *   session:  "session_<id>_<timestamp>"    — handbook sessions aren't version-scoped
 *
 * Generated by pages/api/internal/onlyoffice/config/[id].ts. Callback &
 * force-save recover (type, id, version) from the key echoed by OnlyOffice.
 *
 * Binding draft to source_version at the key level is what prevents
 * delayed saves from a closed editor session from polluting later revisions.
 */
export type OnlyOfficeKeyType = "doc" | "session";

export interface ParsedOnlyOfficeKey {
  type: OnlyOfficeKeyType | string;
  id: string;
  /** OSS version number the session opened on. null for session-type or legacy keys. */
  version: number | null;
}

export function parseOnlyOfficeKey(key: string): ParsedOnlyOfficeKey {
  const parts = key.split("_");
  const type = parts[0] ?? "";
  const id = parts[1] ?? "";
  let version: number | null = null;
  const seg = parts[2];
  if (type === "doc" && seg && seg.startsWith("v")) {
    const n = Number.parseInt(seg.slice(1), 10);
    if (Number.isFinite(n) && n >= 0) version = n;
  }
  return { type, id, version };
}
